# Generated by Django 2.1.1 on 2018-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('shortSum', models.CharField(max_length=5000)),
                ('LongSum', models.CharField(max_length=50000)),
            ],
        ),
    ]
